# Generated by Django 4.2 on 2023-08-11 20:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miniblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='texto',
            new_name='texto_comentario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='post',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='pbkdf2_sha256$600000$ZWBmmjLJ64HgvovibIcKY4$rdOmfes0FsxXWGkOqKwUR7ir5ilnG3amYtIj5CqYWJ8=', max_length=128),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo_electronico',
            field=models.EmailField(default=datetime.datetime(2023, 8, 11, 20, 40, 23, 648244, tzinfo=datetime.timezone.utc), max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_usuario',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
