# Generated by Django 4.2 on 2023-08-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0002_rename_fecha_comentario_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_usuario',
        ),
    ]
