# Generated by Django 4.2 on 2023-08-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0003_remove_usuario_contraseña_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
